### ISSUE TITLE
Workers > Cpus Warning?

### ISSUE THREAD

**Issue by thoersch** [TheClimateCorporation/squeedo#20]
"Work is done asynchronously by workers controlled by the size of the work buffer (currently
   hardcoded to number of cpus minus 1) Bad things happen if you have workers > number of cpus."

The readme is missing this comment found in the source code. Is this accurate? can you define what this means a bit more?

**Comment by jmelching** [comment]
If I remember correctly, if workers > number of cpus, then there isn't enough cpu left to do the controlling logic, ie. controlling who gets work, acking messages back to sqs, and just doing other things.  Its been a few years though, so this is my best recollection.

**Comment by tfendt** [comment]
In our use case, our compute method inserts the message to Postgres so it is not async and as a result :max-concurrent-work option has no effect. The only way to increase the work is to increase the num-workers past the number of cores.

**Comment by jmelching** [comment]
This is only a problem if you have really cpu heavy workers, if you are doing blocking operations that require io you can do waht @tfendt tfendt says.  In general though, i tend to use something like http-async to avoid this blocking all together.
