### ISSUE TITLE
Binary message attributes

### ISSUE THREAD

**Issue by vincentjames501** [TheClimateCorporation/squeedo#30]
Haven't looked into this much, but message attributes should check what the data type of the `MessageAttributeValue` is and call the correct getter.

```clojure
(defn- clojurify-message-attributes [^Message msg]
  (let [javafied-message-attributes (.getMessageAttributes msg)]
    (->> javafied-message-attributes
         (map (fn [[k ^MessageAttributeValue mav]] [(keyword k) (.getStringValue mav)]))
         (into {}))))
```

Untested but possible solution instead of `(.getStringValue mav)`:

```clojure
(case (.getDataType mav)
  "String" (.getStringValue mav)
  "Number" (try
             (BigDecimal. (.getStringValue mav))
             (catch NumberFormatException e
               {:error e :original-value (.getStringValue mav)}))
  "Binary" (.getBinaryValue mav))
```

**Comment by mtkp** [comment]
thanks for catching this @vincentjames501. your possible solution looks good to me, though i think i'd be inclined to handle Number and String the same way (just use `.getStringValue` for both). happy to accept a PR, otherwise i'll look into this when i have time.

**Comment by mtkp** [comment]
@vincentjames501 i think i've got this covered in #35 (see line 180 in sqs.clj)
