### ISSUE TITLE
Create Queue Question

### ISSUE THREAD

**Issue by rodnaph** [TheClimateCorporation/squeedo#34]
Hi.

I had a problem starting a project using this library on AWS which was caused by the fact the role on the EC2 instance didn't have the `sqs:CreateQueue` permission. The queues already existed and are managed with Terraform, so I don't want to give this permission out to the roles. I see at the moment this seems to be because it relies on the fact the Bandalore library provides `create-queue` which returns true if it already exists (but still required the CreateQueue permission).

What are your thoughts on this, would you be open to a PR checking the queues existence first?  Same for dead-letter queue.

Cheers

**Comment by mtkp** [comment]
hi @rodnaph -- thanks for pointing this out. seems reasonable. i'd been planning to move squeedo off bandalore and finally got some time to work on that today. i think 🤞 i've got a fix for this in #35 (see line 86 in sqs.clj)

**Comment by rodnaph** [comment]
Great, looks good - I'll stay tuned for the next release :)

Thanks
