### ISSUE TITLE
Listeners dequeue sqs msgs inside a go block, although dequeue can block the caller thread

### ISSUE THREAD

**Issue by heltonh2r** [TheClimateCorporation/squeedo#37]
I have a scenario with several consumers, the queues are empty except one that has thousands of msgs. I notice that the listener for the non-empty queue is blocking even when the message-channel is not full. 
After some investigations, I saw in the SQS doc [http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-long-polling.html] that SQS receiveMessage method blocks the caller thread, until poll time elapses, if the queue is empty. `If you decide to implement long polling with multiple queues, we recommend using one thread for each queue instead of trying to use a single thread for polling all of the queues.`. 
Because `create-queue-listener` function calls `sqs/dequeue` [that calls receiveMessage with 10secs of long-polling] inside a `async/go` block - which should not have thread blocking, it seams that empty queue listeners are making the consumer of non-empty queues slow. 
Let me know if my conclusion makes sense. 
Thanks for the great library.

**Comment by mtkp** [comment]
@heltonh2r squeedo should set up at least one listener per queue (more specifically, at least one per call to create-consumer), so there should be a thread+ per queue. but it sounds like a possibility that we're using up all the core.async threads. do you have a lot of listeners per queue, or a lot of queues?

**Comment by heltonh2r** [comment]
About 60 queues with 1 listener per queue. We got this problem in test
environment which has more modest machines. As you mentioned, it seams that
listeners of different queues are sharing the same thread. Wouldn't it
safer if the listener code use async/thread instead of async/go to dequeue
msg from SQS, since each listener should run in a different thread?

Em ter, 15 de ago de 2017 20:51, Matt K <notifications@github.com> escreveu:

**Comment by mtkp** [comment]
ah. depending on which version of core.async you've got, the threadpool is probably no more than 50 threads and possibly much less, so it makes sense why you're seeing blocked listeners with 60 queues. your conclusion is correct. we didn't anticipate that many consumers in a single service. as for how to work around this, async/thread is certainly an option. i'll give it some thought.

**Comment by mtkp** [comment]
hi @heltonh2r, i created https://github.com/TheClimateCorporation/squeedo/pull/42 to hopefully address this issue. take a look if you have time. thanks!

**Comment by heltonh2r** [comment]
thanks @mtkp, I'll take look as soon as possible and let you know. For now I increased the system property  `clojure.core.async.pool-size` to meet my requirements.  In fact, should not the `async/thread` obey this same pool-size property as well [which by default is configured to 8]? If so, this change will cause a different behaviour, it will block code execution when core.async's pool is exausted.

**Comment by mtkp** [comment]
`async/thread` uses `async/thread-macro-executor` which is created from [`Executors.newCachedTheadPool`](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Executors.html#newCachedThreadPool(java.util.concurrent.ThreadFactory))  which is an unbounded threadpool (for comparison, this is the same factory method that [clojure.core uses for `future`](https://github.com/clojure/clojure/blob/clojure-1.9.0/src/jvm/clojure/lang/Agent.java#L53)). so fortunately no, its not bounded and wouldn't block execution.

i could just use `future` but it felt better to use `async/thread` since we're working with core.async elsewhere in the namespace.

**Comment by mtkp** [comment]
also, it looks like aws sqs java client will eventually include a true async polling option. so hopefully we can eventually update the go loop implementation to use that (which should be the most efficient option)

**Comment by mtkp** [comment]
@heltonh2r closing this with the release of 1.0.1
